# -*- coding: utf-8 -*-
"""P16_Mabelipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136BRtcv-IJU-3XWx1vvFIXUXpefIKSPT
"""

import math as mt
import numpy as np
import matplotlib.pyplot as plt
#variables de la tierra
xit = 1; yit = 0; vxit = 0; vyit = 2*np.pi;rt = 1
#variables inicial de Júpiter
xij = 5.20; yij = 0; vxij = 0;vyij = (4*mt.pi**2/5.20)**0.5;rj = 5.20

h = 0.004

#función para graficar
def graficas():
  plt.figure(figsize=(6, 6))
  plt.grid()
  plt.scatter(0,0,color='yellow',label='Sol',s=100)
  plt.plot(lyt,lxt,linestyle="--",color="blue")
  plt.scatter(xit,yit,color='blue',label='Tierra')
  plt.plot(lyj,lxj,linestyle="--",color="brown")
  plt.scatter(xij,yij,color='brown',label='Jupiter')
  plt.title("Trayectoria de la tierra y jupiter alrededor del sol")
  plt.xlabel("x (UA)")
  plt.ylabel("y (UA)")
  plt.legend()

#mas valores iniciales
mt = 6.0e24
mj = 1.9e27
ms = 1.989e30
gms = 4*(np.pi)**2
gmj = 4*(mj/ms)*np.pi**2
gmt = 4*(mt/ms)*np.pi**2

#funcion para realizar las ecuaciones, como solo cambia el valor de xi y yi en las ecuaciones llamo a la misma función pero solo cambio x y y cuando las madno llamar
def velypos(vxij,vxit,xij,xit,gms,gmt,gmj,rjt,rtj,h):
  vxj = vxij - h*(gms*xij)/rj**3- h*(gmt*(xij-xit))/rtj**3
  vxt = vxit - h*(gms*xit)/rt**3 - h*gmj*(xit-xij)/rtj**3
  xj = xij + vxj*h
  xt = xit + vxt*h
  return vxj,vxt,xj,xt

#declaracion de listas
lxj=[];lxt=[];lyj=[];lyt=[]

t=0
tf=11.86
#itera mientras llegue a un año de jupiter
while t<tf:
  rt = np.sqrt(xit**2+yit**2)
  rj = np.sqrt(xij**2+yij**2)
  rtj = np.sqrt((xit-xij)**2+(yit-yij)**2)
  vxj,vxt,xj,xt = velypos(vxij,vxit,xij,xit,gms,gmt,gmj,rtj,rtj,h)
  vyj,vyt,yj,yt = velypos(vyij,vyit,yij,yit,gms,gmt,gmj,rtj,rtj,h)
  vxij = vxj ; vxit = vxt ; xij = xj ; xit =xt; yij = yj ; yit =yt ; vyij = vyj ; vyit = vyt
  lyj.append(yj);lxj.append(xj)
  if t<1:  #registra solo para graficar un año terrestre
    lyt.append(yt);lxt.append(xt)
  t+=h

graficar = graficas()